# Generated by Django 5.1.5 on 2025-01-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0002_alter_recipe_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_image",
            field=models.ImageField(upload_to="vege/reciepe"),
        ),
    ]
